jscrambler/jscrambler

packages/jscrambler-cli/src/bin/jscrambler.js

Support the new version pattern (e.g. 5.2-f)

[C-2610] Support the new version pattern

---

packages/jscrambler-cli/src/get-protection-default-fragments.js
packages/jscrambler-cli/src/index.js

Trigger a warning message on the CLI If the growth of the app is bigger than the defined in the threshold.

[C-1835] App Growth Warning

---

packages/jscrambler-cli/src/index.js

This PR attempts to fix some error handling by throwing a errors array instead of logging the errors array and throwing a string.
Before: 
```
// The following three messages are written to the console
Error: "Failed to protect any source file"
Error: "[Annotation Error] Expected " " or end of input but "C" found."in playground.js:1
Error: "Parsing errors on annotations"in playground.js
// The error object is simply {name: "Error", message "Protection failed"}
Error: Protection failed
at Object._callee$ (/home/cmatias/Jscrambler/jscrambler-clients/packages/jscrambler-cli/dist/index.js:438:21)
at tryCatch (/home/cmatias/Jscrambler/jscrambler-clients/packages/jscrambler-cli/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
at Generator.invoke [as _invoke] …
```

improve error handling

---

packages/jscrambler-cli/src/index.js
packages/jscrambler-cli/src/mutations.js

This will prevent race conditions when doing protections in parallel.

feat(cli): use new createApplicationProtection strategy

---

packages/jscrambler-cli/src/bin/jscrambler.js

Validate value of boolean cli arguments.
**Related to** https://github.com/jscrambler/jscrambler/issues/34

fix(cli-arguments): validate bool arguments

---

packages/jscrambler-cli/README.md
packages/jscrambler-cli/src/bin/jscrambler.js
packages/jscrambler-cli/src/cleanup-input-fields.js
packages/jscrambler-cli/src/config.js
packages/jscrambler-cli/src/index.js
packages/jscrambler-cli/src/introspection.js
packages/jscrambler-cli/src/mutations.js

Add ability to set the value of `tolerateMinification` flag in configuration, for use in future Jscrambler versions.

feat(cli): add tolerateMinification flag

---

packages/jscrambler-cli/src/queries.js

deprecation field new to specify sub selection

fix(deprecation): add sub selection

---

packages/jscrambler-cli/src/client.js

feat(cli): add ability to use x-user-authentication header for authentication

Add ability to send auth as header

---

packages/jscrambler-metro-plugin/lib/index.js

feat: identify metro-plugin client

---

packages/jscrambler-cli/README.md
packages/jscrambler-cli/src/bin/jscrambler.js
packages/jscrambler-cli/src/cleanup-input-fields.js
packages/jscrambler-cli/src/index.js

Adds client-side support for the input symbol table option.

Implement input symbol table

---

packages/jscrambler-cli/src/bin/jscrambler.js
packages/jscrambler-cli/src/cleanup-input-fields.js
packages/jscrambler-cli/src/index.js
packages/jscrambler-cli/src/introspection.js
packages/jscrambler-metro-plugin/lib/constants.js
packages/jscrambler-metro-plugin/lib/index.js
packages/jscrambler-metro-plugin/lib/utils.js

Affects jscrambler-cli and jscrambler-metro-plugin

feat(cli): add support for entryPoint

---

packages/grunt-jscrambler/README.md
packages/grunt-jscrambler/examples/simple/Gruntfile.js
packages/grunt-jscrambler/examples/simple/package.json
packages/grunt-jscrambler/tasks/jscrambler.js

This will be called with the protectionId/instrumentationId.

add success callback to grunt task config

---

packages/jscrambler-metro-plugin/lib/index.js

if not supported, add excludeList to gvi when present

fix(metro-plugin): check if api supports excludeList

---

packages/jscrambler-cli/package.json
packages/jscrambler-cli/src/index.js
packages/jscrambler-cli/src/zip.js

feat(jszip): bump

---

packages/jscrambler-cli/src/client.js
packages/jscrambler-cli/src/index.js
packages/jscrambler-cli/src/zip.js

Compress sources content with [jszip](https://stuk.github.io/jszip/documentation/api_jszip/generate_async.html#compression-and-compressionoptions-options) library. 
New env variable METRICS was added to log HTTP requests with payload size and runtime

feat(upload-sources): compress

---

packages/jscrambler-cli/src/index.js

This optimization did not improve the performance as much as we expected, but it adds complexity and worsens already precarious network issues.

fix: revert parallel mode

---

packages/jscrambler-webpack-plugin/README.md
packages/jscrambler-webpack-plugin/src/index.js

https://webpack.js.org/api/compilation-hooks/#processassets

feat(webpack): add support for processAssets hook

---

.changeset/fifty-mails-raise.md
packages/jscrambler-cli/src/index.js

Fs promises to be compatible with older node version

---

.changeset/sweet-cougars-brake.md
packages/jscrambler-cli/package.json
packages/jscrambler-cli/src/client.js
pnpm-lock.yaml

Updated http-proxy-agent and https-proxy-agent (we were using an outdated fork).

feat: update http(S) proxy agent libs

---

.changeset/wet-pears-shout.md
packages/jscrambler-cli/package.json
pnpm-lock.yaml

https://www.cvedetails.com/cve/CVE-2024-39338/

Fix axios vulnerability
