packages/gulp-jscrambler/index.js
**REPEAT OF** jscrambler/gulp-jscrambler#10 :-1: This should have been merged before the creation of this repository.
--
`stream.Transform.prototype.emit` will re-throw errors when there is
no handler.
To avoid that re-throw from ending up in a "unhandled promise
rejection" it is done in the nextTick so the throw will crash the
process, encouraging implementers to handle the error.
--
In shorter terms `.pipe(jScrambler(options))` throwing an error will crash
the process instead of creating a `UnhandledPromiseRejectionWarning`.
Should have been done as part of jscrambler/gulp-jscrambler#6.
=> Do not catch stream error in the promise stack.

packages/grunt-jscrambler/tasks/jscrambler.js
https://github.com/jscrambler/grunt-jscrambler/commit/c76f6b7cffb0188fc83eea4622cbafc9f0df8998 introduced code to handle absolute paths, but it caused the `writeFile` function to attempt to output files that didn't match the current one. This caused an error when we updated our plugin to a version that included this code.
This PR will detect an absolute path and strip the root from it. This then allows the `grunt.file.arePathsEquivalent` check to pass for an absolute path in the same way it does for a relative path.
This is only needed for posix paths, win32 paths include the root for some reason.
=> Fix output absolute path handling in grunt-jscrambler

packages/gulp-jscrambler/index.js, packages/gulp-jscrambler/package-lock.json, packages/gulp-jscrambler/package.json
[gulp-util](https://github.com/gulpjs/gulp-util) has been deprecated.
This change makes gulp-jscrambler compatible with [vinyl-fs](https://github.com/gulpjs/vinyl-fs).
I also updated the package-lock.json. Not sure if that is desirable.
=> Remove gulp-util from gulp-jscrambler.

packages/jscrambler-cli/src/client.js
Previous http request errors were not being caught by us but by axios. With this PR we improve the handling of errors, especially in the case where the user is trying to use an invalid Jscrambler version.
=> [C-3418] Update request error handling

packages/gulp-jscrambler/index.js, packages/gulp-jscrambler/package.json
This pull request is opinionated, but every idea is broken up by commit. I am willing to break this up into multiple pull requests if that is helpful.
* gulp-jscrambler cannot support content streams, because jscrambler-cli assumes that [contents is a buffer](https://github.com/jscrambler/jscrambler/blob/072b8cf802bbfd6c1953c13640efb0fe1475a795/packages/jscrambler-cli/src/zip.js#L52-L55). This is a problem when a user starts the pipeline with `gulp.src('**/*.js', {buffer: false})`. eb0e16c adds a conditional to check for stream mode and error when appropriate.
* The `options` object is passed directly to the protectAndDownload method. I have always been confused why the object was manually constructed. Done by 3e30e41.
* Replaced the "event-stream" dependency with "through2". This is …
=> gulp-jscrambler: Does not Support Streams. Improve Dependencies & Readability.

packages/grunt-jscrambler/package.json, packages/grunt-jscrambler/tasks/jscrambler.js
Lodash dependency is triggering a security vulnerability and its not used by gulp-jscrambler module.
=> fix: unused dep lodash

packages/jscrambler-cli/src/config.js
removed protocol from default config as it is set later in the code.
This will allow users to use `--protocol http` without having to specify the port.
http will map to port 80
https will map to port 443
=> fix(cli): remove protocol from default config

packages/ember-cli-jscrambler/jscrambler-plugin.js, packages/grunt-jscrambler/tasks/jscrambler.js, packages/gulp-jscrambler/index.js, packages/jscrambler-cli/src/client.js, packages/jscrambler-cli/src/config.js, packages/jscrambler-cli/src/index.js, packages/jscrambler-webpack-plugin/src/index.js
Updated `jscrambler-cli` to send a `clientId` on each request. Every client will have a different `clientId`.
=> [C-3978] Add clientId to request header

packages/jscrambler-cli/src/cleanup-input-fields.js
Avoid TypeError with checking for options.tolereteMinification
=> fix(create-application-protection): add default options value when cleaning input fields

packages/jscrambler-cli/package.json, packages/jscrambler-cli/src/bin/jscrambler.js, packages/jscrambler-cli/src/index.js, packages/jscrambler-cli/src/mutations.js
New option code hardening threshold which receives a string with a specific format: {number}{unit='b,kb,mb'}
=> feat(cli): add option code hardening threshold

packages/jscrambler-metro-plugin/lib/index.js, packages/jscrambler-metro-plugin/package.json
Commander helps us read `bundle-output` argument from argv if it is entered in any of the following ways:
`node node_modules/react-native/local-cli/cli.js bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=true --platform='ios' --assets-dest='./ios'`
`node node_modules/react-native/local-cli/cli.js bundle --entry-file index.js --bundle-output ./ios/main.jsbundle --dev true --platform ios --assets-dest ./ios`.
Right now, if bundle command is invoked in the first way we get an error.
=> Added commander for argv handling

packages/jscrambler-cli/src/bin/jscrambler.js, packages/jscrambler-cli/src/index.js
Prevent `useProfilingData: false` from being ignored and set to true.
Now, false/undefined are propagated to the sent data.
=> fix: respect CLI useProfilingData: false

packages/jscrambler-metro-plugin/lib/index.js
it is necessary to be able to use the protection id, so it must be saved in a file to be used later.
=> Save protectionId after protectAndDownload

packages/jscrambler-cli/README.md, packages/jscrambler-cli/package.json
Closes JIRA-ST-502.
Axios module needs to be in the latest version to properly work with proxy + https settings
=> fix(axios): upgrade axios to properly work with proxy + https

packages/jscrambler-metro-plugin/README.md, packages/jscrambler-metro-plugin/lib/index.js
only `bundle` command should trigger obfuscation process
=> fix(metro): skip obfuscation for non-bundle commands

packages/jscrambler-metro-plugin/lib/index.js
This caused an error ('You don't have access to this feature') in every user that din't have access to the it. After the error, the user had no information about how to proceed. 
Now we throw an error with instructions about how to solve the problem.
=> fix(metro-plugin): stop automatically enable of source maps

packages/jscrambler-cli/src/config.js, packages/jscrambler-cli/src/constants.js, packages/jscrambler-cli/src/index.js
Particularly busy VMs can sometimes fail to answer to a request in time.
This is massively annoying during polling as any polling failure can stop the CLI.
=> Retry http requests when faced with gateway timeouts

packages/jscrambler-metro-plugin/lib/constants.js
INIT_CORE_MODULE must use POSIX file notation.
=> fix: issue that was causing entryPoint to break on windows

packages/jscrambler-cli/README.md, packages/jscrambler-cli/src/bin/jscrambler.js, packages/jscrambler-cli/src/index.js
Adds a new option * force-app-environment* that allows user to override the application's environment. Application environment detection an automatic process.
=> feat(cli): add new option to support app environment overriding

packages/jscrambler-webpack-plugin/src/index.js
Removes deprecation message that is shown when using the plugin
=> chore(JscramblerPlugin): replace deprecated plugin() call with hooks.emit.tapAsync()

packages/jscrambler-metro-plugin/lib/utils.js
On Windows, the entry point should include a backslash at the front of the filename, otherwise RN doesn't build.
=> fix: bug on windows preventing react native protections

packages/jscrambler-metro-plugin/lib/index.js, packages/jscrambler-metro-plugin/lib/utils.js
We did support bundles containing the following code:
```js
__d(function(g,r,i,a,m,e,d){
```
This code is produced when bundling for a release, running `./gradlew assembleRelease` for example.
We also want to support debug variants and, in that case the code is not minified and looks like this:
```js
__d(function (global, _$$_REQUIRE, _$$_IMPORT_DEFAULT, _$$_IMPORT_ALL, module, exports, _dependencyMap) {
```
This PR updates the regex to collect these identifiers so we can support both variants.
=> fix(metro-plugin): update regex to handle non minified bundles

packages/jscrambler-cli/src/index.js
There is no need to wait for the application to be updated since we are also sending sources on `createApplicationProtection`.
Do this in parallel so can spare some time waiting for nothing.
In the future, we can even move the updateApplicationSource to the backend and update them when are creating a new protection.
=> feat(cli): update application sources at the same time that we create the protection

packages/jscrambler-cli/src/index.js
This bug started to happening [in this PR](https://github.com/jscrambler/jscrambler/pull/115), when we reverted a change  but forgot this use case.
=> [CD-7334] instrument-and-download: correctly use updateApplicationSources function

packages/jscrambler-webpack-plugin/src/index.js
Allows passing regular expressions / functions to the `chunks` option.
This should allow users to have more flexibility when choosing which chunks to protect.
=> [ST-2348] allow regex/function filters

packages/jscrambler-cli/src/index.js, packages/jscrambler-cli/src/introspection.js, packages/jscrambler-cli/src/mutations.js
The application update function (jscrambler-cli/src/index.js > updateApplication) was removing values from the payload, causing areSubscribersOrdered to not be returned in some responses.
Related to CD-8334.
=> Fix: updateApplication function not sending areSubscribersOrdered in data

.changeset/wicked-stingrays-shop.md, packages/ember-cli-jscrambler/package.json, packages/grunt-jscrambler/package.json, packages/gulp-jscrambler/package.json, packages/jscrambler-cli/package.json, packages/jscrambler-metro-plugin/package.json, packages/jscrambler-webpack-plugin/package.json
Renovate bot (and possibly other tools) is failing to display our CHANGELOGs properly.
It's possible that the monorepo structure is confusing the bot.
NPM has a standard way to indicate where a package lives, so we can and should fill it.
See also: https://github.com/renovatebot/renovate/issues/2926#issuecomment-575094237
=> Register package directory to assist tooling like Renovate bot.

.changeset/gentle-pets-flow.md, packages/jscrambler-cli/README.md
Added the newly developed `--delete-protection-on-success` flag to the README.
=> Docs: added delete-protection-on-success flag to the readme

.changeset/short-hats-serve.md, packages/jscrambler-cli/src/index.js
I'm a user of jscrambler and tried to use the option `deleteProtectionOnSuccess` but the protections were never deleted because the operation to delete is async and the code needs to await for it. We need this fix in in a patch version, otherwise our VM fills up very quickly and have to manually delete the protections every few weeks.
=> fix: await to delete protection on success

.changeset/eighty-rocks-juggle.md, packages/jscrambler-cli/README.md, packages/jscrambler-cli/src/client.js
* add `proxy.protocol` option (http by default)
=> fix(jscrambler-cli): missing proxy protocol option

.changeset/many-sheep-cover.md, packages/gulp-jscrambler/index.js
Empty files were causing errors on gulp-jscrambler.
=> Empty files should not be protected

.changeset/old-knives-behave.md, packages/gulp-jscrambler/index.js
There is no need to push the empty files array if empty files were not found.
=> Empty files array should not be pushed if empty

.changeset/great-nails-reply.md, packages/gulp-jscrambler/README.md, packages/gulp-jscrambler/index.js
Enable option allow the user to manipulate files sources and allow to skip jscrambler protection.
=> Enable option on gulp jscrambler

.changeset/fluffy-lions-explode.md, packages/jscrambler-metro-plugin/lib/sourceMaps.js
* create a reactive-native project with `react-native init test` command
* change metro.config.js file to include jscrambler-plugin and allow comments
```
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
const jscramblerMetroPlugin = require("jscrambler-metro-plugin")();
/**
* Metro configuration
* https://reactnative.dev/docs/metro
*
* @type {import('metro-config').MetroConfig}
*/
const config = { 
// if you have other metro configs, add here
...jscramblerMetroPlugin,
transformer: {
minifierConfig: {
compress: false,
output: {
comments: true
}
}
}
};
module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```
* add `.jscramblerrc` with antiTampering and enable sourceMaps
`TypeError: Column must be greater than or equal to 0, got -16`
In the …
=> chore(metro-plugin): columnStart should only be applied to first line

.changeset/violet-suns-hammer.md, packages/jscrambler-cli/package.json
Remove unused dependencies. 
temp dependency has rimraf@2.6.2, which in turn depends on glob@7.2.0, which depends on minimatch@3.0.4, which is vulnerable.
axios and jszip have vulnerabilites, bumped.
=> fix: remove unused dependencies

.changeset/tiny-paws-sip.md, packages/jscrambler-cli/src/bin/jscrambler.js
Mode is a setting that should only be used on versions 8.4 and after.
So, we should have a clear error on the CLI covering the cases where it does not, otherwise , the error will come from the API and be too confusing.
=> fix: add error when using mode with version <8.4

.changeset/lovely-news-pull.md, package.json, packages/jscrambler-cli/package.json, pnpm-lock.yaml
It was necessary to temporarily override (using pnpm overrides: https://pnpm.io/package_json#pnpmoverrides) the version of the cross-spawn library due to the fact that the foreground-child library, which is higher on the dependency chain, has, in its most recent patch, the cross-spawn library set to the 7.0.3 version in the package-lock that they publish, that being a vulnerable version.
=> [CD-9308]: Force cross spawn dep to have version 7.0.6

.changeset/cool-months-move.md, packages/jscrambler-cli/src/utils.js
The option cwd is currently only used for writing purposes (after protection).
However, in the beforeProtection entries, it is concatenated to the target files, while the verification for file existence is made without the concatenation, leading to the prepend/append never happening to the targeted file.
=> Fix beforeProtection and cwd options compatibility
